### ISSUE TITLE
Issue when using required_docs on a project with ephemeral models

### ISSUE THREAD

**Issue by john-jerome** [tnightengale/dbt-meta-testing#5] opened 2021-04-13 17:04 UTC
I'm getting this error when running `dbt run-operation required_docs` on our dbt project in which we have some ephemeral models.

```
Running with dbt=0.19.1
Checking `required_tests` config...
Encountered an error while running operation: Compilation Error in macro required_docs (macros/required_docs.sql)
  Operations can not ref() ephemeral nodes, but company_billie_limits__update__seller_financing_limit is ephemeral
  
  > in macro default__evaluate_required_docs (macros/utils/required_docs/evaluate_required_docs.sql)
  > called by macro evaluate_required_docs (macros/utils/required_docs/evaluate_required_docs.sql)
  > called by macro default__required_docs (macros/required_docs.sql)
  > called by macro required_docs (macros/required_docs.sql)
```
A possible workaround is to add `config(required_docs=False)` to each ephemeral model, but it might be easier to just exclude them already at the macro level.

**Comment by tnightengale** [comment] 2021-04-13 17:29
@john-jerome Thanks for finding this! I'll open up a branch with a fix! The intended behaviour should ignore ephemeral models :)

**Comment by tnightengale** [comment] 2021-05-03 15:39
FIxed by https://github.com/tnightengale/dbt-meta-testing/releases/tag/0.2.1

**Closed by tnightengale** 2021-05-03 15:39 UTC
